config/routes.rb
Rails.application.routes.draw do
  get 'analyticspage/analytics'
  resources :appointments
  resources :profiles
  resources :patients
  devise_for :users
  # get 'landingpage/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Default rooting on page load
  root 'landingpage#index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/profiles/:id', to: 'profiles#show', as: 'profile_user'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:show, :edit, :update, :destroy]
  def signedinuserprofile profile =
      Profile.find_by_user_id(current_user.id)
    if profile.nil?
      redirect_to "/profiles/new"
    else
        # @profile = Profile.find_by_user_id(current_user.id)
        # redirect_to "/profiles/#{@profile.id}"
        # else if the user already has a profile then direct to the home page!
        redirect_to root_path
    end
  end

  helper_method :counter_patients
  helper_method :redirection_profile


  def counter_patients
      puts "Tiggered"
      @patient_user_counter = Patient.where(user_id: current_user).select(:user_id).count
  end

  def redirection_profile
      @idProfile = Profile.where(user_id: current_user).select(:id)
      redirect_to "/profiles/#{@idProfile}"
  end

  # GET /profiles
  # GET /profiles.json
  def index
    # redirect user away from profiles
    @profiles = Profile.all
    redirect_to root_path
    flash[:error] = "Restricted Area"
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
      # @profile = Profile.find_by_user_id(current_user.id)
      # redirect_to "/profiles/#{@profile.id}"
  end

  # GET /profiles/new
  def new
      @profile = Profile.new
      puts current_user.id

      respond_to do |format|
          format.html #new.html.erb
          format.json {
              render json: @profile
           }
       end
   end

  # GET /profiles/1/edit
  def edit
      @profile.user = current_user
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = Profile.new(profile_params)
    @profile.user_id = current_user.id

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Profile was successfully created.' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def profile_params
      params.require(:profile).permit(:firstname, :lastname, :address, :pps_number, :dental_license)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= simple_form_for(@profile) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :address %>
    <%= f.input :pps_number, :label => "PPS" %>
    <%= f.input :dental_license %>
  </div>

  <div class="form-actions">
      <div style="display: flex; float: left;">
          <%= link_to 'Back', @profile, class: "btn btn-dark btn-m" %>
      </div>
      <div style="display: flex; float: right;">
          <%= f.button :submit , class: "btn btn-success btn-m" %>
      </div>
  </div>

<% end %>

app/views/profiles/edit.html.erb
<%= render 'partials/navbar' %>
<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Edit your profile
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', profile: @profile %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">
    </div>
</div>
<br><br>
<%= render 'partials/footer' %>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Address</th>
      <th>PPS number</th>
      <th>Dental license</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.firstname %></td>
        <td><%= profile.lastname %></td>
        <td><%= profile.address %></td>
        <td><%= profile.pps_number %></td>
        <td><%= profile.dental_license %></td>
        <td><%= profile.user %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<hr class="colorgraph">
<div class="jumbotron" id="signup_jumbo">

<h2 style= "text-align: center">Now, we create your profile <b><%= current_user.email.split('@')[0] %><b>!</h2><br>

<%= render 'form', profile: @profile %>

</div>
<hr class="colorgraph">

app/views/profiles/show.html.erb
<%= render 'partials/navbar' %>

<br/><br/>
<div class="container ">
    <div class="jumbotron ">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                <img src="https://www.svgimages.com/svg-image/s5/man-passportsize-silhouette-icon-256x256.png" alt="stack photo" class="img">
            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                <div class="container" style="border-bottom:1px solid black">
                    <h2 style="text-align:center;">
                        <%= MasterDecorator.new(@profile).concat_first_name_last_name %>
                    </h2>
                </div>
                <hr>

                <ul class="container details">
                    <!--  email address -->
                    <li><p ><span class="fas fa-envelope " style="width:50px;" data-toggle="tooltip" data-placement="top" title="Tooltip on top"></span><%= current_user.email %></p></li>
                    <!-- Address -->
                    <li><p><span class="fas fa-map-marker-alt" style="width:50px;"></span>Address : <%= @profile.address %></p></li>
                    <!-- PPS Number -->
                    <li><p><span class="far fa-id-card" style="width:50px;" title="Tools" ></span>PPS Number : <%= MasterDecorator.new(@profile).pps_number_to_uppercase %></p></li>
                    <!-- Dental License id -->
                    <li><p><span class="far fa-id-badge" style="width:50px;"></span>Dental License : <%= @profile.dental_license%></p></li>
                    <!-- Number of Patients -->
                    <li><p><span class="fas fa-users" style="width:50px;"></span>Number of Patients : <%= counter_patients %></p></li>

                </ul>
            </div>
        </div>
    </div>
    <div style="display: flex; justify-content: center;">
        <%= link_to 'Back', root_path, class: "btn btn-secondary btn-m" %>   |
        <%= link_to 'Edit Profile', edit_profile_path(@profile), class: "btn btn-secondary btn-m" %> |
        <%= link_to "Cancel my account", registration_path(resource_name), data: { confirm: "Are you sure?" }, method: :delete, class: "btn btn-danger btn-m" %>
    </div>
</div>

<%= render 'partials/footer' %>