config/routes.rb
Rails.application.routes.draw do
  get 'analyticspage/analytics'
  resources :appointments
  resources :profiles
  resources :patients
  devise_for :users
  # get 'landingpage/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Default rooting on page load
  root 'landingpage#index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/profiles/:id', to: 'profiles#show', as: 'profile_user'
end

app/controllers/landingpage_controller.rb
require 'twitter'

class LandingpageController < ApplicationController
  # Define tweet client
  def index
      username = 'IrishDentists'
      @glob_username = username
      options = {:count => 3, :include_rts => true}

      @tweets = $client.user_timeline(username, options)

      @last_record_patient = Patient.where

      puts @tweets
  end

  # Get the last record current user added
  def last_record
      @last_r = Patient.where(:user_id=>[current_user.id]).order('created_at DESC').first.Full_Name
  end
  # Get the id of the last record of patient added
  def last_record_id
      @last_r_id = Patient.where(:user_id=>[current_user.id]).order('created_at DESC').first.id
  end
  # Conditional to check if any patients exists
  def is_patients_exists?
      patient_size = Patient.where(:user_id=>[current_user.id]).order('created_at DESC').size
      if patient_size > 0
          true
      else
          false
      end
  end

  helper_method :last_record
  helper_method :last_record_id
  helper_method :is_patients_exists?
end

app/helpers/landingpage_helper.rb
module LandingpageHelper
end

app/views/landingpage/index.html.erb
<%= render 'partials/navbar' %>

<div class="jumbotron jumbotron-fluid">
    <div id="outercard">
        <div class="card" style="width: 90%; display:block; margin:auto; border-radius: 5px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
            <div class="image-placeholder-left">
                <%= image_tag ("landing.jpg"), class:"im"%>
            </div>

            <div class ="text-placeholder-right">
              <div class="">
                  <div class = "text-region" style="padding-left: 17px; padding-right: 17px;">
                      <h3> Welcome back Dr <%= current_user.profile.firstname %>!</h3>
                      <!-- We add a conditional here to check if there is any records in the database to prevent an error for the new user -->
                      <% if is_patients_exists? %>
                        <h6>You recently added the patient:  <b><i><%= last_record %></i></b>, you can view their profile here : <%= link_to 'view', patient_path(last_record_id), class:"btn btn-dark btn-m" %></h6>
                      <% else %>
                        <h6> You have no patients, you can add a patient here : <%= link_to 'Add', new_patient_path, class:"btn btn-dark btn-m" %> </h6>
                      <% end %>
                      <!-- Administrator can download all pdf's in the reports folder! -->
                      <% if current_user.admin? %>
                        <h6> You are an Admin, you can see some analytics here :<%= link_to 'view', analyticspage_analytics_path, class:"btn btn-dark btn-m" %> </h6>
                      <% end %>
                  </div>
              </div>
            </div>
        </div>
    </div>
  <div class = "bottom_container" style="margin-top: 5em; display:flex; flex-direction: row; justify-content: center; align-items: center">
          <% @tweets.each do |tweet| %>
              <div class="card" style="width: 24rem; height: 20em; margin-right: 4em; margin-left: 4em; border-radius: 15px 50px 30px; box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);">
               <div class="card-body">
                 <h5 class="card-title"><%= image_tag ("twitter.png"), class: 'twt-icon'%> </h5>
                 <h6 id = "twitter-uname" class="card-subtitle mb-2 text-muted">@<%= @glob_username %></h6>
                 <p class="card-text" style="font-size: 14px; text-muted "><i>" <%= tweet.text %> "</i></p>
               </div>
               <div class ="time-tweet" style ="float: right; align-text: right; border-top: 2px solid #38A1F3; ">
                   <h7 class ="date-tag" style="font-size: 12px; padding-top: 1em;"><%= MasterDecorator.new(tweet).display_time_for_tweet %></h7>
               </div>
             </div>
         <% end %>
  </div>
</div>

<%= render 'partials/footer' %>