config/routes.rb
Rails.application.routes.draw do
  get 'analyticspage/analytics'
  resources :appointments
  resources :profiles
  resources :patients
  devise_for :users
  # get 'landingpage/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Default rooting on page load
  root 'landingpage#index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/profiles/:id', to: 'profiles#show', as: 'profile_user'
end

app/views/partials/_footer.html.erb
<footer>
  <div class="footer-copyright text-center py-3">© 2019 Copyright:
    <a href="google.com"> Thehighwayclinic.com</a>
  </div>
  <div id="openweathermap-widget-13" style="float: right; padding-right: 10px; padding-bottom: 7px;"></div>
<script>
    window.myWidgetParam ? window.myWidgetParam : window.myWidgetParam = [];
    window.myWidgetParam.push({id: 13,cityid: '2964574',appid: '<%= ENV['WEATHERAPI'] %>',units: 'metric',containerid: 'openweathermap-widget-13',
    });
    // code sourced here : https://openweathermap.org/widgets-constructor
    (function() {
        var script = document.createElement('script');
        script.async = true;script.charset = "utf-8";
        script.src = "//openweathermap.org/themes/openweathermap/assets/vendor/owm/js/weather-widget-generator.js";
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(script, s);
    })();
</script>
</footer>

app/views/partials/_login_page_links.html.erb
<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name), class: "btn btn-secondary btn-m" %><br />
<% end %>
<br/>
<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name), class: "btn btn-secondary btn-m" %><br />
<% end %>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="#">Thehighwayclinic</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to("Home", root_path , :class => "nav-link")%>
          </li>
          <li class="nav-item active">
              <%= link_to('Profile', profile_path(current_user.profile.id), :class => "nav-link") %>
          </li>
          <li class="nav-item active">
            <%= link_to("My Patients", patients_path , :class => "nav-link")%>
          </li>
          <li class="nav-item active">
            <%= link_to("My Appointments", appointments_path, :class => "nav-link") %>
          </li>
          <!-- This section is only for the Administrator -->
          <% if current_user.admin? %>
              <li class="nav-item active">
                <%= link_to("Analytics", analyticspage_analytics_path, :class => "nav-link") %>
              </li>
          <% end %>
        </ul>
        <h7 id = "nav-bar-current-user-email" style="color: white; margin-right: 20px;"> Welcome! <%= current_user.email %> </h7>

        <form class="form-inline mt-2 mt-md-0">

          <br>
          <br>
          <%= link_to('Log out', destroy_user_session_path, :method => :delete, :class => "btn btn-outline-info") %>
        </form>
      </div>
</nav>

app/views/partials/_sign_up_links.html.erb
<br/>
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name), class: "btn btn-secondary btn-m" %><br />
<% end %>