config/routes.rb
Rails.application.routes.draw do
  get 'analyticspage/analytics'
  resources :appointments
  resources :profiles
  resources :patients
  devise_for :users
  # get 'landingpage/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # Default rooting on page load
  root 'landingpage#index'
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'
  get '/profiles/:id', to: 'profiles#show', as: 'profile_user'
end

app/models/patient.rb
class Patient < ApplicationRecord
  belongs_to :user
  has_many :appointments
end

app/controllers/patients_controller.rb
require 'jordanreport'
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /patients
  # GET /patients.json
  def index
    # If search param has a name
    if params[:Full_Name]
        # Query if theres a record like the one specified AND user_id == current_user within devise helper
        @patients = Patient.where('"Full_Name" LIKE :name AND patients.user_id = :id', {:name => "%#{params[:Full_Name]}%", :id => current_user.id})
        # another if to check if the patients instance has a size zero meaning no results
        if @patients.size == 0
            # if this condition is true then return all patients of that user!
            @patients = current_user.patients.all
        end
    else
        # If no search param (example, on page load) is provided then return all patients belong to current_user
        @patients = current_user.patients.all
    end
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
    @patient.user = current_user

    # invoke our gem
    Report_Logging_JM.writes(@patient)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:Full_Name, :Age, :Sex, :Address, :PPS, :Medical_Card)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<%= simple_form_for(@patient) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :Full_Name %>
    <%= f.input :Age %>
    <%= f.input :Sex , :collection => %w[M F]%>
    <%= f.input :Address %>
    <%= f.input :PPS, :label => "PPS" %>
    <%= f.input :Medical_Card, :collection => %w[YES NO] %>
  </div>

  <div class="form-actions">
      <div style="display: flex; float: left;">
          <%= link_to 'Back', patients_url, class: "btn btn-dark btn-m" %>
      </div>
      <div style="display: flex; float: right;">
          <%= f.button :submit , class: "btn btn-success btn-m" %>
      </div>
  </div>
<% end %>

app/views/patients/edit.html.erb
<%= render 'partials/navbar' %>

<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Change Patient Details
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', patient: @patient %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">

    </div>

</div>
<br><br>

<%= render 'partials/footer' %>

app/views/patients/index.html.erb
<%= render 'partials/navbar' %>

<div class="jumbotron jumbotron-fluid">
<div class="container">

<h1 style="text-align: center;">My Patients</h1>

<div id="top-container">
    <!-- adding patient to database -->
    <div id="patient_add" style="float: right"><%= link_to 'New Patient', new_patient_path, class: "btn btn-success btn-m" %></div>
    <!-- Search bar for searching patients -->
    <div id="search_bar" style="float: left">
        <!-- Search bar -->
        <%= form_tag(patients_path, :method => "get") do %>
            <div class="input-group add-on">
              <%= text_field_tag :Full_Name, params[:Full_Name], class: 'form-control' %>
                <div class="input-group-btn">
                    <%= button_tag 'Search', name: nil, class: 'btn btn-default' do %>
                        <i class="fas fa-search"></i>
                    <% end %>
                </div>
            </div>
        <% end %>
    </div>
</div>
<br>
<br>

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Full name</th>
      <th scope="col">Age</th>
      <th scope="col">Sex</th>
      <th scope="col">Address</th>
      <th scope="col">PPS</th>
      <th scope="col">Medical card</th>
      <th scope="col">Dentist</th>
      <th scope="col">Show</th>
      <th scope="col">Edit</th>
      <th scope="col">Delete</th>
      <th scope="col">Reports</th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.Full_Name %></td>
        <td><%= patient.Age %></td>
        <td><%= patient.Sex %></td>
        <td><%= patient.Address %></td>
        <td><%= patient.PPS %></td>
        <%= MasterDecorator.new(patient.Medical_Card).medical_card_status_index(patient.Medical_Card) %>
        <td><%= MasterDecorator.new(patient.user.email).email_address_split(patient.user.email) %></td>
        <td><%= link_to 'Show', patient %></td>
        <td><%= link_to 'Edit', edit_patient_path(patient) %></td>
        <td><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%= link_to 'Report', "/reports/#{patient.Full_Name}.pdf", class: "btn btn-dark btn-m" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

</div>
</div>

<%= render 'partials/footer' %>

app/views/patients/new.html.erb
<%= render 'partials/navbar' %>

<br>
<div class="container">
    <div class="jumbotron">
        <div class="row">
            <div class="col-md-12">
                <div class="container" >
                    <h2 style="text-align:center;">
                        Adding a Patient
                    </h2>
                </div>
                <hr class="colorgraph">
                <ul class="container details">
                    <%= render 'form', patient: @patient %>
                </ul>
            </div>
        </div>
        <hr class="colorgraph">

    </div>

</div>
<br><br>
<%= render 'partials/footer' %>

app/views/patients/show.html.erb
<%= render 'partials/navbar' %>

<br/><br/>
<div class="container ">
    <div class="jumbotron ">
        <div class="row">
            <div class="col-md-4 col-xs-12 col-sm-6 col-lg-4">
                <%= image_tag ("drip-patient-pictogram.svg"), class: "patient-view"%>

            </div>
            <div class="col-md-8 col-xs-12 col-sm-6 col-lg-8">
                <div class="container">
                    <h2 style="text-align:center;">
                        <%= @patient.Full_Name %>
                    </h2>
                </div>
                <hr class="colorgraph">

                <ul class="container details">
                    <!--  Patient's age -->
                    <li><p>Age : <%= @patient.Age %></p></li>
                    <!-- Patient's address -->
                    <li><p>Address : <%= @patient.Address %></p></li>
                    <!-- Patient's sex -->
                    <li><p>Sex : <%= @patient.Sex %></p></li>
                    <!-- Patient's address -->
                    <li><p>Dental License : <%= @patient.Address %></p></li>
                    <!-- Patient's pps -->
                    <li><p>PPS Number :  <%= @patient.PPS %></p></li>
                    <!-- Patient's medical card status -->
                    <%= MasterDecorator.new(@patient.Medical_Card).medical_card_status_show(@patient.Medical_Card) %>

                </ul>
            </div>
        </div>
    </div>
    <div style="display: flex; justify-content: center;">
        <%= link_to 'Back', patients_path , class: "btn btn-dark btn-m"%> |
        <%= link_to 'Edit', edit_patient_path(@patient), class: "btn btn-warning btn-m" %>
    </div>
</div>
<%= render 'partials/footer' %>